"""Included image_url field

Revision ID: 4a657a31466e
Revises: 714d52a28f9b
Create Date: 2025-06-05 10:38:09.134219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a657a31466e'
down_revision = '714d52a28f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=200), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
